[package]
name = "bardic-ipc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
bardic-core = { path = "../bardic-core" }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = "0.37.2"
