name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build
        run: cargo build --workspace --all-targets

      - name: Run tests
        run: cargo test --workspace --lib --tests

      - name: Clippy (lint)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Format check
        run: cargo fmt --all -- --check
